version: "3.8"

services:
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - db
    network_mode: host

  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 31234
    volumes:
      - /mysql_data:/var/lib/mysql
    network_mode: host


