version: "3.8"

services:
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - db
    network_mode: host
  db:
    image: mysql
    restart: always
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 31234
      MYSQL_DATABASE: data
    network_mode: host

volumes:
  dbdata:

