openapi: "3.0.3"
info:
  title: "testtask API"
  description: "testtask API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/testtask"
    description: local server
paths:
  /api/auth:
    post:
      summary: "POST api/auth"
      operationId: "authenticateUser"
      requestBody:
        description: Login and password hash
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "OK"
  /api/message:
    post:
      summary: "POST api/message"
      operationId: "saveMessage"
      parameters:
        - in: header
          name: token
          schema:
            type: string
      requestBody:
        description: Login and password hash
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                message:
                  type: string
      responses:
        "200":
          description: "OK"